replicaCount: 2
# Deployment configuration
deployment:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
image:
  repository: "us-west1-docker.pkg.dev/prj-devops-anmol/generic-testing-repo/react-app"
  pullPolicy: IfNotPresent
  tag: "5a5b73726ecf170249e85eef5ab0bf0b11c48fae" # updating CI/CD pipeline should override this with commit SHA
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
# Container configuration
container:
  port: 80
  name: react-app
  env: []
  volumeMounts: []
  args: []
  command: []
# Volume configuration
volumes: []
# Health check configuration
healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
serviceAccount:
  create: true
  annotations: {}
  name: ""
  automountServiceAccountToken: false
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
nameOverride: react-app
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: false # Disabled since we are using GKE Gateway
  className: ""
  annotations: {}
  hosts: []
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
networkPolicy:
  enabled: false
podDisruptionBudget:
  enabled: false
  minAvailable: 1
security:
  podSecurityStandards:
    enforce: "restricted"
    audit: "restricted"
    warn: "restricted"
  annotations: {}
# GKE Gateway (instead of Ingress)
gateway:
  enabled: true
  name: gke-gateway-external-lb
  namespace: dev
