apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app   # Unique in ArgoCD
  namespace: argocd     # Always argocd namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/bishtpooja908/Argocd-helm-repo.git'
    path: helm-charts/react-helm
    targetRevision: feature/helm-charts-deployments
    helm:
      valueFiles:
        - react-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev      
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
